name: spotto
description: A predictive parking app prototype
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  fl_chart: ^0.68.0
  google_fonts: ^6.3.2
  phosphor_flutter: ^2.0.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
